---
title: "ATMP analysis"
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(knitr)
library(flextable)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(dplyr.summarise.inform = FALSE)
options(knitr.kable.NA = '') # Suppress printing of NA in kable
# Standard theme for document 
theme_set(theme_bw()) 

set_flextable_defaults(
align = "center",
digits = 2
# theme_fun = theme_zebra
  )

doShiny = TRUE

# source("atmp.R")

# Läs in från Excel
# indata = open_indata("models.xlsx")
library(tidyverse)
library(writexl)

# Spara till excel
# TODO: Ta bort pars och använd global_table
pars= list(
  risk = 0.045 ,
  ränta = 0.0 ,
  progr = .1 ,
  time_horizon = 20
)


global_table = read_csv("
name, value
hazard, 0.045 
discount, 0.03 
firm_discount, 0.0
threshold, 1
time_horizon, 20,
active_plan, 1, 
control_plan, 2
"
) 

global_table_rnames = global_table %>% column_to_rownames(var = "name") 

QoL = c(1, 1, 0.9, 0.5, 0.1, 0)

treatment_description = read_csv("
name, title, value,                      description
plan, Plan,        ,               Plan number combining Treatment and Contract 
name, Treatment,    ,              Treatment name
p_HU, Failure hazard, 0,    Probability of progression starting
p_HD, Death,          0,     Probability of dying with full health
p_UD, Death in prog., 0,     Probability of dying in progression state
health_states, Health states,  0,      Number of health states
QoL_column, QoL Column, ,          Name of column in QoL table (non-linear progression)
QoL_start, QoL Start,   1,    Initial QoL
QoL_end, QoL End,       0,    Final QoL
random_state, Random state, 1, Which state is the random state. To model progression before treatment
")

# Allow for simple modification. 
# TODO: Should do this using the same method as Shiny
# 
survive_share = 0.5
survive_time = 15

health_states = 6
death_p = 0.01
time_horizon = 20

p_HU = 0.04
p_HD = death_p
p_UD = death_p

treatment_table = read_csv("
plan, name, p_HU, p_HD, p_UD, health_states
1, ATMP,              0.05, 0, 0, 4
0, Comparison,        0.99, 0, 0, 4
") %>% 
  mutate(
    p_HD = 0.01 , 
    p_UD = 0.02 ,
    health_states = health_states, 
  )
treatment_table[[1,3]] = p_HU

contract_description = read_csv("
name, title, value,               description
plan, Plan, ,                Plan number combining Treatment and Contract 
name, Contract, ,            Contract name
tot_payment,  Tot.Payment, 0,     Total payment or yearly paymentif payment is continuous
cont_payment, Cont. payment, 0, Payment each year that the patient is alive (traditional) 
cost_trend, Cost Trend,      0, Cost trend over time, for continuous payment
contract_length, Periods,   20, Total length of contract
initial_payment, Payment,   0,    Share of payment in initial period
refund, Refund,             0, Share of payments refunded upon failure (progression)
start, Start,               1, State where contract begins (ex: additional treatment in progression) 
end, End,                   2, State where contract ends
aggregate_failure, Agg.Fail, 0, Threshold share of population for aggregate failure
")

contract_table = read_csv("
plan, name,tot_payment, cont_payment,     contract_length,initial_payment,refund, start, end, cost_trend
1, ATMP conditional, 10,0,        10,0,             0, 1,2,0
1, Payment progr., 0,0.1,      0,0,             0,2,4,0
0, Comparison,0,0.1,            0,0,             0,1,4,0
") %>% select(-cost_trend)

state_table = read_csv("
name,   state,    hazard,   QoL,  death_hazard
ATMP,   1,        0.05,     1.0,    0.01
ATMP,   2,        1.00,     0.66,    0.02
ATMP,   3,        1.00,     0.33,    0.02
ATMP,   4,        0.00,     0.0,    0.02
")

indata = list(
    treatment_table = treatment_table  ,
    contract_table = contract_table  ,
    global_table = global_table,
    treatment_description = treatment_description ,
    contract_description = contract_description ,
    state_table =state_table 
  )

# global_table = read_excel("models.xlsx", sheet = "Globals")

models = list(
  Globals = global_table ,
  Treatments = treatment_table , 
  Contracts = contract_table , 
  QoL = tibble(QoL1 = QoL),
  States = state_table,
  Treatment_fields = treatment_description, 
  Contract_fields = contract_description
)

# write_xlsx(models, "examples.xlsx")
# indata = open_indata("examples.xlsx")

```

## Treatment table

```{r}
indata$treatment_table %>% 
  with_titles( indata$treatment_description) %>% 
  flextable_output() %>% 
  colformat_double(j = c(1,6), digits = 0) 
```

## Payment table

```{r, eval=TRUE}
indata$contract_table %>% 
  select(-initial_payment, -refund) %>% 
  with_titles( indata$contract_description) %>% 
  flextable_output()  %>% 
  colformat_double(j = c(1,5,6,7), digits = 0) 
```

# Analysis

```{r, knitr.kable.na = ' '}
rubriker = c(Treatment = "name", Payment = "contract")
 contract_analysis(indata, show_details = TRUE) %>% 
   select(-plan) %>% rename(any_of(rubriker)) %>% 
  flextable_output() 
```

### Simple result

```{r, knitr.kable.na = ' '}
rubriker = c(Behandling = "name", Payment = "contract")
 contract_analysis(indata) %>% rename(any_of(rubriker)) %>% 
  flextable_output() 
```

## Input table

```{r}
mod_table = read_csv("
table_name, row_name, column_name, value 
global_table,  firm_discount, value, 0.03
global_table,  firm_discount, value, 0.10
treatment_table,  ATMP, p_HU, 0.00
treatment_table,  ATMP, p_HU, 0.01
treatment_table,  ATMP, p_HU, 0.05
contract_table,  ATMP conditional, contract_length, 1.00
contract_table,  ATMP conditional, contract_length, 5.00
contract_table,  ATMP conditional, contract_length, 10.00
")

mod_table %>% 
  flextable_output() 
```

# Results

```{r}
compare_with_variations(indata, mod_table ) %>% 
  rename(Hazard = p_HU, Length = contract_length, Jämförelse = Treatments, Costdiff. = Cost, QALYdiff. = QALY)  %>% rename(firm_discount = value) %>% 
  select(-Jämförelse) %>% 
   flextable_output()  
```


# Payments over time

```{r}
df =  contract_analysis(indata, over_time = TRUE) 

df %>% rename(Contract = contract) %>% 
  ggplot() + 
  aes(time, Cost, fill = Contract) + 
  geom_col()  + facet_grid(rows = vars(name)) +
  labs(x = "")
```


